const mockDb = {
  user: {
    getById: jest.fn(),
    getByUsername: jest.fn(),
    getByEmail: jest.fn(),
    create: jest.fn(),
  },
  topic: {
    getAll: jest.fn().mockResolvedValue(['topic1', 'topic2']),
  },
  community: {
    doesExistById: jest.fn(),
    doesExistByName: jest.fn(),
    getById: jest.fn(),
    getByName: jest.fn(),
    isPrivate: jest.fn(),
    create: jest.fn(),
    isOwner: jest.fn(),
    getModInfo: jest.fn(),
    editCommunitySettings: jest.fn(),
  },
  recentCommunities: {
    assign: jest.fn(),
  },
  userCommunity: {
    isMember: jest.fn(),
    getById: jest.fn(),
    join: jest.fn(),
    leave: jest.fn(),
    getMembersByName: jest.fn(),
    getMembers: jest.fn(),
    fetchHomePageBy: jest.fn(),
    getJoinedCommunities: jest.fn(),
  },
  userChat: {
    isMemberById: jest.fn(),
    read: jest.fn(),
    leave: jest.fn(),
    muteChat: jest.fn(),
  },
  chat: {
    getById: jest.fn(),
    doesExist_1on1: jest.fn(),
    canCreateChat: jest.fn(),
    create: jest.fn(),
  },
  communityModerator: {
    isMod: jest.fn(),
    getById: jest.fn(),
    delete: jest.fn(),
    makeMod: jest.fn(),
    deactivateMod: jest.fn(),
  },
  postModeration: {
    moderate: jest.fn(),
    updateModeration: jest.fn(),
    updatePostAsModerator: jest.fn(),
  },
  commentModeration: {
    moderate: jest.fn(),
    updateModeration: jest.fn(),
  },
  communityFlair: {
    getAllPostFlairs: jest.fn(),
    getAllCommunityFlairs: jest.fn(),
    doesExistByName: jest.fn(),
    getById: jest.fn(),
    getPostFlairCount: jest.fn(),
    getCommunityFlairCount: jest.fn(),
    fetch: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
    delete: jest.fn(),
  },
  bannedUsers: {
    isBanned: jest.fn(),
  },
  post: {
    getById: jest.fn(),
    getByIdAndModerator: jest.fn(),
    create: jest.fn(),
    edit: jest.fn(),
    getByIdAndCommunity: jest.fn(),
    getPopular: jest.fn(),
    getBy: jest.fn(),
    deletePost: jest.fn(),
  },
  postVote: {
    hasVoted: jest.fn(),
    create: jest.fn(),
    getById: jest.fn(),
    update: jest.fn(),
    delete: jest.fn(),
    vote: jest.fn(),
  },
  comment: {
    getById: jest.fn(),
    getByIdAndModeration: jest.fn(),
    create: jest.fn(),
    softDelete: jest.fn(),
    delete: jest.fn(),
    getCommentThreads: jest.fn(),
    getMoreReplies: jest.fn(),
    update: jest.fn(),
    getByIdAndCommunityId: jest.fn(),
  },
  commentVote: {
    getById: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
    delete: jest.fn(),
  },
  postAssignedFlair: {
    getById: jest.fn(),
    hasPostFlair: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
    delete: jest.fn(),
  },
  userAssignedFlair: {
    getById: jest.fn(),
    getUserFlairInCommunity: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
    delete: jest.fn(),
  },
  joinRequest: {
    hasRequested: jest.fn(),
    request: jest.fn(),
    delete: jest.fn(),
  },
  modMail: {
    sendMessage: jest.fn(),
    getById: jest.fn(),
    update: jest.fn(),
  },
  message: {
    send: jest.fn(),
  },
  approvedUser: {
    isApproved: jest.fn(),
    create: jest.fn(),
    delete: jest.fn(),
  },
  savedPost: {
    fetch: jest.fn(),
    isSaved: jest.fn(),
    save: jest.fn(),
    unsave: jest.fn(),
  },
  savedComment: {
    fetch: jest.fn(),
    isSaved: jest.fn(),
    save: jest.fn(),
    unsave: jest.fn(),
  },
  report: {
    getBy: jest.fn(),
    updateAllPendingReports: jest.fn(),
    alreadyReported: jest.fn(),
    report: jest.fn(),
  },
  notification: {
    getById: jest.fn(),
    fetchBy: jest.fn(),
    hasUnread: jest.fn(),
    send: jest.fn(),
    read: jest.fn(),
    openAll: jest.fn(),
    markAllAsRead: jest.fn(),
    hide: jest.fn(),
  },
};

export default mockDb;
